name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main
  workflow_dispatch:  

# Variables globales
env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: nasa-rag
  LAMBDA_FUNCTION: query

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Descargar código
      - name: Checkout code
        uses: actions/checkout@v4
      
      # 2. Autenticar con AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      # 3. Login a ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      # 4. Build y push imagen Docker
      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --provenance=false \
            --sbom=false \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            --push \
            .
      
      # 5. Actualizar y luego espera a la funcion Lambda
      - name: Update Lambda function
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.LAMBDA_FUNCTION }} \
            --image-uri $ECR_REGISTRY/$ECR_REPOSITORY:latest
           
          aws lambda wait function-updated \
            --function-name ${{ env.LAMBDA_FUNCTION }} \
            --region ${{ env.AWS_REGION }}


      # --------- Notis ------------------      
      
      # 6.  Sucess
      - name: Success notification
        if: success()
        run: |
          echo "Deploy completado!"
          echo " URL: https://jn3779aza9.execute-api.us-east-1.amazonaws.com"
      
      # 7. Si falla
      - name: Failure notification
        if: failure()
        run: echo " Deploy falló. Revisa los logs."